### PR TITLE
ch08: Fix footnote. Fix mixed brackets.

### PR DESCRIPTION
**Pull request by paitonic**
- changed `<span class=footnote"...` to `<span data-type="footnote"` (footnote is incorrectly shown in PDF version, I assume this should fix it)
- from  "...in the `[0, n)` range"  to "...in the `[0, n]` range"

### CODE REVIEW

**Comment by bevacqua** [comment]
-1 to the second bit, `[0, n)` is correct. It means `0` is included in the output range but `n` isn't. It's not mixed brackets, it's maths notation

**Comment by bevacqua** [comment]
You reverted the wrong change 😅

**Comment by paitonic** [comment]
I fixed the change. Does this looks better?

**Comment by bevacqua** [comment]
Thanks. Sorry for the delay

**Pull request merged**
